export const ratings = [
  {
    category: 'Динамическая зарядка',
    items: [
      {rank: 1, name: 'Иван Иванов', energy: 52},
      {rank: 2, name: 'Сергей Смирнов', energy: 50},
      {rank: 3, name: 'Ольга Кузнецова', energy: 47},
      {rank: 4, name: 'Елена Новикова', energy: 45},
      {rank: 5, name: 'Александр Фёдоров', energy: 44},
      {rank: 6, name: 'Мария Попова', energy: 42},
      {rank: 7, name: 'Анна Соколова', energy: 41},
      {rank: 8, name: 'Алексей Морозов', energy: 40},
      {rank: 9, name: 'Юлия Васильева', energy: 39},
      {rank: 10, name: 'Николай Петров', energy: 38},
      {rank: 11, name: 'Татьяна Михайлова', energy: 36},
      {rank: 12, name: 'Игорь Крылов', energy: 35},
    ],
  },
  {
    category: 'Интенсивное кардио',
    items: [
      {rank: 1, name: 'Дмитрий Орлов', energy: 75},
      {rank: 2, name: 'Владимир Никитин', energy: 72},
      {rank: 3, name: 'Андрей Волков', energy: 70},
      {rank: 4, name: 'Светлана Зайцева', energy: 67},
      {rank: 5, name: 'Евгений Герасимов', energy: 65},
      {rank: 6, name: 'Александр Мельников', energy: 63},
      {rank: 7, name: 'Оксана Фролова', energy: 62},
      {rank: 8, name: 'Павел Данилов', energy: 61},
      {rank: 9, name: 'Людмила Сорокина', energy: 60},
      {rank: 10, name: 'Ирина Беляева', energy: 58},
      {rank: 11, name: 'Григорий Савельев', energy: 57},
      {rank: 12, name: 'Лидия Чернова', energy: 55},
    ],
  },
  {
    category: 'Упражнения на пресс',
    items: [
      {rank: 1, name: 'Михаил Романов', energy: 100},
      {rank: 2, name: 'Екатерина Антонова', energy: 98},
      {rank: 3, name: 'Максим Тихонов', energy: 95},
      {rank: 4, name: 'Валерия Виноградова', energy: 93},
      {rank: 5, name: 'Олег Лебедев', energy: 90},
      {rank: 6, name: 'Наталья Бородина', energy: 89},
      {rank: 7, name: 'Виктория Дмитриева', energy: 87},
      {rank: 8, name: 'Станислав Игнатьев', energy: 85},
      {rank: 9, name: 'Алёна Андреева', energy: 84},
      {rank: 10, name: 'Виктор Павлов', energy: 82},
      {rank: 11, name: 'Алиса Ершова', energy: 80},
      {rank: 12, name: 'Артём Власов', energy: 78},
    ],
  },
  {
    category: 'Упражнения на спину',
    items: [
      {rank: 1, name: 'Илья Рябов', energy: 40},
      {rank: 2, name: 'Марина Захарова', energy: 38},
      {rank: 3, name: 'Георгий Козлов', energy: 36},
      {rank: 4, name: 'Василиса Широкова', energy: 35},
      {rank: 5, name: 'Артемий Ушаков', energy: 33},
      {rank: 6, name: 'Полина Киселёва', energy: 32},
      {rank: 7, name: 'Марат Зуев', energy: 31},
      {rank: 8, name: 'Ксения Логинова', energy: 30},
      {rank: 9, name: 'Юрий Шестаков', energy: 29},
      {rank: 10, name: 'Елизавета Лазарева', energy: 28},
      {rank: 11, name: 'Софья Яковлева', energy: 27},
      {rank: 12, name: 'Константин Наумов', energy: 26},
    ],
  },
  {
    category: 'Упражнения на ноги',
    items: [
      {rank: 1, name: 'Наталия Васильева', energy: 148},
      {rank: 2, name: 'Глеб Киселёв', energy: 145},
      {rank: 3, name: 'Анастасия Крылова', energy: 143},
      {rank: 4, name: 'Семён Лапин', energy: 140},
      {rank: 5, name: 'Вероника Фомина', energy: 138},
      {rank: 6, name: 'Роман Литвинов', energy: 135},
      {rank: 7, name: 'Дарья Гаврилова', energy: 133},
      {rank: 8, name: 'Виктор Степанов', energy: 130},
      {rank: 9, name: 'Лариса Николаева', energy: 128},
      {rank: 10, name: 'Евгений Алексеев', energy: 125},
      {rank: 11, name: 'Злата Кулакова', energy: 122},
      {rank: 12, name: 'Олег Семёнов', energy: 120},
    ],
  },
];
